# shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.dotfiles

# all of our zsh files
typeset -U config_files
config_files=($ZSH/**/*.zsh)

for file in $config_files
do
  source $file
done

# load the path files
#for file in ${(M)config_files:#*/path.zsh}
#do
#  source $file
#done
#
## load everything but the completion files
#for file in ${config_files:#*/completion.zsh}
#do
#  source $file
#done
#
## load every completion after autocomplete loads
#for file in ${(M)config_files:#*/completion.zsh}
#do
#  source $file
#done

unset config_files

autoload -U compinit
compinit

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source zshlocal file if exists
if [[ -f ~/.zshlocal ]]; then;
    source ~/.zshlocal
fi

# hotkeys for command search
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^R' history-incremental-search-backward
